import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexCLientProvider } from "@/provider/convex-client-provider";
import { Toaster } from "@/components/ui/toaster";
import { ModalProvider } from "@/provider/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <ConvexCLientProvider>
            <Toaster />
            <ModalProvider />
            {children}
          </ConvexCLientProvider>
          
        </body>
      </html>
  );
}
